// Code generated by gen-html; DO NOT EDIT.

package html

import "github.com/ernlel/gomb"

// Named constructors for every standard HTML element.
// Each accepts optional children (*gomb.Element) and attributes (gomb.Attr) inline:
//
//   Div(Attr{Key: "class", Value: "container"}, H1(Txt("Hello")))
//   Div().Attr("class", "container").Children(H1().Text("Hello"))
//
// Both styles are equivalent — use whichever reads best.

// Anchor creates a <a> element.
func Anchor(args ...interface{}) *gomb.Element { return buildElement("a", args) }

// Abbr creates a <abbr> element.
func Abbr(args ...interface{}) *gomb.Element { return buildElement("abbr", args) }

// Address creates a <address> element.
func Address(args ...interface{}) *gomb.Element { return buildElement("address", args) }

// Area creates a <area> element.
func Area(args ...interface{}) *gomb.Element { return buildElement("area", args) }

// Article creates a <article> element.
func Article(args ...interface{}) *gomb.Element { return buildElement("article", args) }

// Aside creates a <aside> element.
func Aside(args ...interface{}) *gomb.Element { return buildElement("aside", args) }

// Audio creates a <audio> element.
func Audio(args ...interface{}) *gomb.Element { return buildElement("audio", args) }

// B creates a <b> element.
func B(args ...interface{}) *gomb.Element { return buildElement("b", args) }

// Base creates a <base> element.
func Base(args ...interface{}) *gomb.Element { return buildElement("base", args) }

// Bdi creates a <bdi> element.
func Bdi(args ...interface{}) *gomb.Element { return buildElement("bdi", args) }

// Bdo creates a <bdo> element.
func Bdo(args ...interface{}) *gomb.Element { return buildElement("bdo", args) }

// Blockquote creates a <blockquote> element.
func Blockquote(args ...interface{}) *gomb.Element { return buildElement("blockquote", args) }

// Body creates a <body> element.
func Body(args ...interface{}) *gomb.Element { return buildElement("body", args) }

// Br creates a <br> element.
func Br(args ...interface{}) *gomb.Element { return buildElement("br", args) }

// Button creates a <button> element.
func Button(args ...interface{}) *gomb.Element { return buildElement("button", args) }

// Canvas creates a <canvas> element.
func Canvas(args ...interface{}) *gomb.Element { return buildElement("canvas", args) }

// Caption creates a <caption> element.
func Caption(args ...interface{}) *gomb.Element { return buildElement("caption", args) }

// Cite creates a <cite> element.
func Cite(args ...interface{}) *gomb.Element { return buildElement("cite", args) }

// Code creates a <code> element.
func Code(args ...interface{}) *gomb.Element { return buildElement("code", args) }

// Col creates a <col> element.
func Col(args ...interface{}) *gomb.Element { return buildElement("col", args) }

// Colgroup creates a <colgroup> element.
func Colgroup(args ...interface{}) *gomb.Element { return buildElement("colgroup", args) }

// DataElement creates a <data> element.
func DataElement(args ...interface{}) *gomb.Element { return buildElement("data", args) }

// Datalist creates a <datalist> element.
func Datalist(args ...interface{}) *gomb.Element { return buildElement("datalist", args) }

// Dd creates a <dd> element.
func Dd(args ...interface{}) *gomb.Element { return buildElement("dd", args) }

// Del creates a <del> element.
func Del(args ...interface{}) *gomb.Element { return buildElement("del", args) }

// Details creates a <details> element.
func Details(args ...interface{}) *gomb.Element { return buildElement("details", args) }

// Dfn creates a <dfn> element.
func Dfn(args ...interface{}) *gomb.Element { return buildElement("dfn", args) }

// Dialog creates a <dialog> element.
func Dialog(args ...interface{}) *gomb.Element { return buildElement("dialog", args) }

// Div creates a <div> element.
func Div(args ...interface{}) *gomb.Element { return buildElement("div", args) }

// Dl creates a <dl> element.
func Dl(args ...interface{}) *gomb.Element { return buildElement("dl", args) }

// Dt creates a <dt> element.
func Dt(args ...interface{}) *gomb.Element { return buildElement("dt", args) }

// Em creates a <em> element.
func Em(args ...interface{}) *gomb.Element { return buildElement("em", args) }

// Embed creates a <embed> element.
func Embed(args ...interface{}) *gomb.Element { return buildElement("embed", args) }

// Fieldset creates a <fieldset> element.
func Fieldset(args ...interface{}) *gomb.Element { return buildElement("fieldset", args) }

// Figcaption creates a <figcaption> element.
func Figcaption(args ...interface{}) *gomb.Element { return buildElement("figcaption", args) }

// Figure creates a <figure> element.
func Figure(args ...interface{}) *gomb.Element { return buildElement("figure", args) }

// Footer creates a <footer> element.
func Footer(args ...interface{}) *gomb.Element { return buildElement("footer", args) }

// Form creates a <form> element.
func Form(args ...interface{}) *gomb.Element { return buildElement("form", args) }

// H1 creates a <h1> element.
func H1(args ...interface{}) *gomb.Element { return buildElement("h1", args) }

// H2 creates a <h2> element.
func H2(args ...interface{}) *gomb.Element { return buildElement("h2", args) }

// H3 creates a <h3> element.
func H3(args ...interface{}) *gomb.Element { return buildElement("h3", args) }

// H4 creates a <h4> element.
func H4(args ...interface{}) *gomb.Element { return buildElement("h4", args) }

// H5 creates a <h5> element.
func H5(args ...interface{}) *gomb.Element { return buildElement("h5", args) }

// H6 creates a <h6> element.
func H6(args ...interface{}) *gomb.Element { return buildElement("h6", args) }

// Head creates a <head> element.
func Head(args ...interface{}) *gomb.Element { return buildElement("head", args) }

// Header creates a <header> element.
func Header(args ...interface{}) *gomb.Element { return buildElement("header", args) }

// Hgroup creates a <hgroup> element.
func Hgroup(args ...interface{}) *gomb.Element { return buildElement("hgroup", args) }

// Hr creates a <hr> element.
func Hr(args ...interface{}) *gomb.Element { return buildElement("hr", args) }

// Html creates a <html> element.
func Html(args ...interface{}) *gomb.Element { return buildElement("html", args) }

// I creates a <i> element.
func I(args ...interface{}) *gomb.Element { return buildElement("i", args) }

// Iframe creates a <iframe> element.
func Iframe(args ...interface{}) *gomb.Element { return buildElement("iframe", args) }

// Img creates a <img> element.
func Img(args ...interface{}) *gomb.Element { return buildElement("img", args) }

// InputElement creates a <input> element.
func InputElement(args ...interface{}) *gomb.Element { return buildElement("input", args) }

// Ins creates a <ins> element.
func Ins(args ...interface{}) *gomb.Element { return buildElement("ins", args) }

// Kbd creates a <kbd> element.
func Kbd(args ...interface{}) *gomb.Element { return buildElement("kbd", args) }

// Label creates a <label> element.
func Label(args ...interface{}) *gomb.Element { return buildElement("label", args) }

// Legend creates a <legend> element.
func Legend(args ...interface{}) *gomb.Element { return buildElement("legend", args) }

// Li creates a <li> element.
func Li(args ...interface{}) *gomb.Element { return buildElement("li", args) }

// Link creates a <link> element.
func Link(args ...interface{}) *gomb.Element { return buildElement("link", args) }

// MainElement creates a <main> element.
func MainElement(args ...interface{}) *gomb.Element { return buildElement("main", args) }

// MapElement creates a <map> element.
func MapElement(args ...interface{}) *gomb.Element { return buildElement("map", args) }

// Mark creates a <mark> element.
func Mark(args ...interface{}) *gomb.Element { return buildElement("mark", args) }

// MenuElement creates a <menu> element.
func MenuElement(args ...interface{}) *gomb.Element { return buildElement("menu", args) }

// Meta creates a <meta> element.
func Meta(args ...interface{}) *gomb.Element { return buildElement("meta", args) }

// MeterElement creates a <meter> element.
func MeterElement(args ...interface{}) *gomb.Element { return buildElement("meter", args) }

// Nav creates a <nav> element.
func Nav(args ...interface{}) *gomb.Element { return buildElement("nav", args) }

// Noscript creates a <noscript> element.
func Noscript(args ...interface{}) *gomb.Element { return buildElement("noscript", args) }

// ObjectElement creates a <object> element.
func ObjectElement(args ...interface{}) *gomb.Element { return buildElement("object", args) }

// Ol creates a <ol> element.
func Ol(args ...interface{}) *gomb.Element { return buildElement("ol", args) }

// Optgroup creates a <optgroup> element.
func Optgroup(args ...interface{}) *gomb.Element { return buildElement("optgroup", args) }

// Option creates a <option> element.
func Option(args ...interface{}) *gomb.Element { return buildElement("option", args) }

// OutputElement creates a <output> element.
func OutputElement(args ...interface{}) *gomb.Element { return buildElement("output", args) }

// P creates a <p> element.
func P(args ...interface{}) *gomb.Element { return buildElement("p", args) }

// Param creates a <param> element.
func Param(args ...interface{}) *gomb.Element { return buildElement("param", args) }

// Picture creates a <picture> element.
func Picture(args ...interface{}) *gomb.Element { return buildElement("picture", args) }

// Portal creates a <portal> element.
func Portal(args ...interface{}) *gomb.Element { return buildElement("portal", args) }

// Pre creates a <pre> element.
func Pre(args ...interface{}) *gomb.Element { return buildElement("pre", args) }

// Progress creates a <progress> element.
func Progress(args ...interface{}) *gomb.Element { return buildElement("progress", args) }

// Q creates a <q> element.
func Q(args ...interface{}) *gomb.Element { return buildElement("q", args) }

// Rp creates a <rp> element.
func Rp(args ...interface{}) *gomb.Element { return buildElement("rp", args) }

// Rt creates a <rt> element.
func Rt(args ...interface{}) *gomb.Element { return buildElement("rt", args) }

// Ruby creates a <ruby> element.
func Ruby(args ...interface{}) *gomb.Element { return buildElement("ruby", args) }

// S creates a <s> element.
func S(args ...interface{}) *gomb.Element { return buildElement("s", args) }

// Samp creates a <samp> element.
func Samp(args ...interface{}) *gomb.Element { return buildElement("samp", args) }

// ScriptElement creates a <script> element.
func ScriptElement(args ...interface{}) *gomb.Element { return buildElement("script", args) }

// Search creates a <search> element.
func Search(args ...interface{}) *gomb.Element { return buildElement("search", args) }

// Section creates a <section> element.
func Section(args ...interface{}) *gomb.Element { return buildElement("section", args) }

// SelectElement creates a <select> element.
func SelectElement(args ...interface{}) *gomb.Element { return buildElement("select", args) }

// Slot creates a <slot> element.
func Slot(args ...interface{}) *gomb.Element { return buildElement("slot", args) }

// Small creates a <small> element.
func Small(args ...interface{}) *gomb.Element { return buildElement("small", args) }

// Source creates a <source> element.
func Source(args ...interface{}) *gomb.Element { return buildElement("source", args) }

// Span creates a <span> element.
func Span(args ...interface{}) *gomb.Element { return buildElement("span", args) }

// Strong creates a <strong> element.
func Strong(args ...interface{}) *gomb.Element { return buildElement("strong", args) }

// StyleElement creates a <style> element.
func StyleElement(args ...interface{}) *gomb.Element { return buildElement("style", args) }

// Sub creates a <sub> element.
func Sub(args ...interface{}) *gomb.Element { return buildElement("sub", args) }

// Summary creates a <summary> element.
func Summary(args ...interface{}) *gomb.Element { return buildElement("summary", args) }

// Sup creates a <sup> element.
func Sup(args ...interface{}) *gomb.Element { return buildElement("sup", args) }

// Table creates a <table> element.
func Table(args ...interface{}) *gomb.Element { return buildElement("table", args) }

// Tbody creates a <tbody> element.
func Tbody(args ...interface{}) *gomb.Element { return buildElement("tbody", args) }

// Td creates a <td> element.
func Td(args ...interface{}) *gomb.Element { return buildElement("td", args) }

// TemplateElement creates a <template> element.
func TemplateElement(args ...interface{}) *gomb.Element { return buildElement("template", args) }

// Textarea creates a <textarea> element.
func Textarea(args ...interface{}) *gomb.Element { return buildElement("textarea", args) }

// Tfoot creates a <tfoot> element.
func Tfoot(args ...interface{}) *gomb.Element { return buildElement("tfoot", args) }

// Th creates a <th> element.
func Th(args ...interface{}) *gomb.Element { return buildElement("th", args) }

// Thead creates a <thead> element.
func Thead(args ...interface{}) *gomb.Element { return buildElement("thead", args) }

// TimeElement creates a <time> element.
func TimeElement(args ...interface{}) *gomb.Element { return buildElement("time", args) }

// TitleElement creates a <title> element.
func TitleElement(args ...interface{}) *gomb.Element { return buildElement("title", args) }

// Tr creates a <tr> element.
func Tr(args ...interface{}) *gomb.Element { return buildElement("tr", args) }

// Track creates a <track> element.
func Track(args ...interface{}) *gomb.Element { return buildElement("track", args) }

// U creates a <u> element.
func U(args ...interface{}) *gomb.Element { return buildElement("u", args) }

// Ul creates a <ul> element.
func Ul(args ...interface{}) *gomb.Element { return buildElement("ul", args) }

// VarElement creates a <var> element.
func VarElement(args ...interface{}) *gomb.Element { return buildElement("var", args) }

// Video creates a <video> element.
func Video(args ...interface{}) *gomb.Element { return buildElement("video", args) }

// Wbr creates a <wbr> element.
func Wbr(args ...interface{}) *gomb.Element { return buildElement("wbr", args) }
