// Command gen-html generates elements_gen.go in the html/ package.
// It produces a named constructor function for every standard HTML element.
//
// Usage:
//
//	go run ./tools/gen-html
//
// Each function returns a gomb.Element:
//
//	func Div(args ...interface{}) gomb.Element { return buildElement("div", args) }
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// all standard HTML elements.
var elements = []string{
	// void elements (self-closing)
	"area", "base", "br", "col", "embed", "hr", "img", "input",
	"link", "meta", "param", "source", "track", "wbr",

	// normal elements
	"a", "abbr", "address", "article", "aside", "audio",
	"b", "bdi", "bdo", "blockquote", "body", "button",
	"canvas", "caption", "cite", "code", "colgroup",
	"data", "datalist", "dd", "del", "details", "dfn", "dialog",
	"div", "dl", "dt",
	"em",
	"fieldset", "figcaption", "figure", "footer", "form",
	"h1", "h2", "h3", "h4", "h5", "h6", "head", "header", "hgroup", "html",
	"i", "iframe", "ins",
	"kbd",
	"label", "legend", "li",
	"main", "map", "mark", "menu", "meter",
	"nav", "noscript",
	"object", "ol", "optgroup", "option", "output",
	"p", "picture", "portal", "pre", "progress",
	"q",
	"rp", "rt", "ruby",
	"s", "samp", "script", "search", "section", "select",
	"slot", "small", "span", "strong", "style", "sub", "summary", "sup",
	"table", "tbody", "td", "template", "textarea", "tfoot", "th", "thead",
	"time", "title", "tr",
	"u", "ul",
	"var", "video",
}

func funcName(tag string) string {
	switch tag {
	case "a":
		return "Anchor"
	case "var":
		return "VarElement"
	case "map":
		return "MapElement"
	case "object":
		return "ObjectElement"
	case "template":
		return "TemplateElement"
	case "select":
		return "SelectElement"
	case "input":
		return "InputElement"
	case "style":
		return "StyleElement"
	case "script":
		return "ScriptElement"
	case "title":
		return "TitleElement"
	case "output":
		return "OutputElement"
	case "data":
		return "DataElement"
	case "time":
		return "TimeElement"
	case "main":
		return "MainElement"
	case "menu":
		return "MenuElement"
	case "meter":
		return "MeterElement"
	default:
		return strings.ToUpper(tag[:1]) + tag[1:]
	}
}

func main() {
	sort.Strings(elements)

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by gen-html; DO NOT EDIT.

package html

import "github.com/ernlel/gomb"

// Named constructors for every standard HTML element.
// Each accepts optional children (gomb.Element) and attributes (gomb.Attr) inline:
//
//   Div(Attr{Key: "class", Value: "container"}, H1(Txt("Hello")))
//   Div().Attr("class", "container").Children(H1().Text("Hello"))
//
// Both styles are equivalent — use whichever reads best.
`)

	for _, tag := range elements {
		name := funcName(tag)
		fmt.Fprintf(&buf, "\n// %s creates a <%s> element.\n", name, tag)
		fmt.Fprintf(&buf, `func %s(args ...interface{}) gomb.Element { return buildElement("%s", args) }`+"\n", name, tag)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, "format error:", err)
		os.Stdout.Write(buf.Bytes())
		os.Exit(1)
	}

	target := "../../pkg/html/elements_gen.go"
	if len(os.Args) > 1 {
		target = os.Args[1]
	}

	if err := os.WriteFile(target, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write error:", err)
		os.Exit(1)
	}

	fmt.Printf("wrote %s (%d elements)\n", target, len(elements))
}
